### ISSUE TITLE
[setup] styled-system implementation

### ISSUE THREAD

**Issue by leeuwis** [storyofams/next-boilerplate#34]
Use the [default implementation](https://styled-system.com/getting-started) of `styled-system`. 

At the moment the implementation feels overly complex and does not have a lot of added value. If the only benefit is the use of aliases (which can also be confusing), I would suggest to switch to the default implementation.

**Comment by jescowuester** [comment]
If you're thinking about shaking this up, I've been using tailwind at resumedia and like it a lot better now than styled-system. 
You do lose the flexibility of being able to use custom values (like `px="20px"`), and classNames can't be typechecked (unlike styled system). So in some places, we need to use inline styles or scoped style tags. 
I was also afraid that it would make the markup harder to read since all your styles are inlined, but so far that hasn't been the case.

Tailwind has a lower level of abstraction which makes it easier to debug and I can use normal HTML elements instead of `Box` everywhere. It also feels much more productive and I typically end up with a smaller css bundle. Vscode also has really good tailwind IntelliSense / linting so the typechecking is not a big issue.

**Comment by aidana12** [comment]
I do agree that default implementation would be better, plus it might eliminate some bug(s) we have with aliases. 


Regarding Tailwind, I find it incredibly unreadable:
`display={isBooking ? 'none' : {_: 'block', lg: 'flex'}}
flexDirection={{_: 'column', lg: 'row'}}
pt={{_: isDetailed || addGuest ? 0 : 5, lg: 8}}
px={{_: isDetailed || addGuest ? 0 : 4, lg: 0}}`
vs
class={`display-${isBooking ? 'none': 'block'} lg:display-${isBooking ? 'none': 'block'} flexDirection-column  flexDirection-row pt-${isDetailed || addGuest ? 0 : 5} lg:pt-${isDetailed || addGuest ? 0 : 8}  px-${isDetailed || addGuest ? 0 : 4} lg:pt-0`}

Not sure if maybe you think differently, but that is way too long and not visually structured at all. Yes, sure the example I used is a bit complex, but it's not that bad and very much readable vs what I would have done with Tailwind. Sure, I could create a new file, make a styled component but passing props, writing out that code plus the media queries and conditions, that would have taken me way more time. Also, with so little structure and visual separation of code, I cannot for the life in me visualise the component in the second scenario and most of what I'm doing is just changing padding and display. 

I'd hate to see what this looks like with tailwind:
`height={{_: '210px', md: '400px', lg: '100%'}}
width={{_: 'auto', lg: '100%'}}
flex={{_: 'auto', lg: '1'}}
order={{_: 1, lg: 2}}
bg="white"
transition="left 0.18s ease-in-out, right 0.18s ease-in-out, top 0.18s ease-in-out, opacity 0.18s ease-in-out"
position={{_: 'absolute', lg: 'static'}}
left={{_: isDetailed ? 0 : '24px', lg: 'unset'}}
right={{_: isDetailed ? 0 : '24px', lg: 'unset'}}
top={{_: isDetailed ? 0 : '60px', lg: 'unset'}}
zIndex={isDetailed ? 2 : 0}
opacity={{_: isDetailed ? 1 : 0, lg: 1}}`

When debugging, mobile for example, I inspect the site, I see I don't like the top, imagine how much code I'd have to scan to find the top class. Sure I can search, but it'll still take me a few seconds to find the right component, the right mq and the right condition. Especially for QA periods and SLA, with picky customers and not detail oriented people building, saving these seconds would add up to so much saved time and also would literally save my sanity.

Besides my rant above, I also really dislike the fact that it's not typed :D

**Comment by jescowuester** [comment]
```
className={`
	${isBooking ? 'hidden' : 'block lg:hidden'}
    ${isDetailed || addGuest ? 'pt-0 pb-0' : 'pt-5 pb-4'} lg:pt-8 lg:pb-0
	flex-col lg:flex-row
`}
```

👆 tailwind :D

**Comment by MrBamBam** [comment]
#49
